
namespace TyphoonAdapter.DCC
{
    public class NMRAManufacturers
    {
        public static string Get(byte value)
        {
            switch (value)
            {
                case 0: return "NMRA";
                case 1: return "CML Electronics Limited";
                case 2: return "Train Technology";
                case 3: return "";
                case 4: return "";
                case 5: return "";
                case 6: return "";
                case 7: return "";
                case 8: return "";
                case 9: return "";
                case 10: return "";
                case 11: return "NCE Corporation (formerly North Coast Engineering)";
                case 12: return "Wangrow Electronics";
                case 13: return "Public Domain & Do-It-Yourself Decoders";
                case 14: return "PSI –Dynatrol";
                case 15: return "Ramfixx Technologies (Wangrow)";
                case 16: return "";
                case 17: return "Advance IC Engineering";
                case 18: return "JMRI";
                case 19: return "AMW";
                case 20: return "T4T – Technology for Trains GmbH";
                case 21: return "Kreischer Datentechnik";
                case 22: return "KAM Industries";
                case 23: return "S Helper Service";
                case 24: return "MoBaTron.de";
                case 25: return "Team Digital, LLC";
                case 26: return "MBTronik – PiN GITmBH";
                case 27: return "MTH Electric Trains, Inc.";
                case 28: return "Heljan A/S";
                case 29: return "Mistral Train Models";
                case 30: return "Digsight";
                case 31: return "Brelec";
                case 32: return "Regal Way Co. Ltd";
                case 33: return "Praecipuus";
                case 34: return "Aristo-Craft Trains";
                case 35: return "Electronik & Model Produktion";
                case 36: return "DCCconcepts";
                case 37: return "NAC Services, Inc";
                case 38: return "Broadway Limited Imports, LLC";
                case 39: return "Educational Computer, Inc.";
                case 40: return "KATO Precision Models";
                case 41: return "Passmann";
                case 42: return "Digirails";
                case 43: return "Ngineering";
                case 44: return "SPROG-DCC";
                case 45: return "ANE Model Co, Ltd";
                case 46: return "GFB Designs";
                case 47: return "Capecom";
                case 48: return "Hornby Hobbies Ltd";
                case 49: return "Joka Electronic";
                case 50: return "N&Q Electronics";
                case 51: return "DCC Supplies, Ltd";
                case 52: return "Krois-Modell";
                case 53: return "Rautenhaus Digital Vertrieb";
                case 54: return "TCH Technology";
                case 55: return "QElectronics GmbH";
                case 56: return "LDH";
                case 57: return "Rampino Elektronik";
                case 58: return "KRES GmbH";
                case 59: return "Tam Valley Depot";
                case 60: return "Bluecher-Electronic";
                case 61: return "TrainModules";
                case 62: return "Tams Elektronik GmbH";
                case 63: return "Noarail";
                case 64: return "Digital Bahn";
                case 65: return "";
                case 66: return "Railnet Solutions, LLC";
                case 67: return "";
                case 68: return "MAWE Elektronik";
                case 69: return "";
                case 70: return "";
                case 71: return "New Youk Byano Limited";
                case 72: return "";
                case 73: return "The Electric Railroad Company";
                case 74: return "";
                case 75: return "";
                case 76: return "";
                case 77: return "";
                case 78: return "";
                case 79: return "";
                case 80: return "";
                case 81: return "";
                case 82: return "";
                case 83: return "";
                case 84: return "";
                case 85: return "Uhlenbrock GmbH";
                case 86: return "";
                case 87: return "RR-Cirkits";
                case 88: return "";
                case 89: return "";
                case 90: return "";
                case 91: return "";
                case 92: return "";
                case 93: return "";
                case 94: return "";
                case 95: return "Sanda Kan Industrial, Ltd.";
                case 96: return "";
                case 97: return "Doehler & Haas";
                case 98: return "";
                case 99: return "Lenz Elektronik GmbH";
                case 100: return "";
                case 101: return "Bachmann Trains";
                case 102: return "";
                case 103: return "Nagasue System Design Office";
                case 104: return "";
                case 105: return "Computer Dialysis France";
                case 106: return "";
                case 107: return "";
                case 108: return "";
                case 109: return "Viessmann Modellspielwaren GmbH";
                case 110: return "";
                case 111: return "Haber & Koenig Electronics GmbH (HKE)";
                case 112: return "";
                case 113: return "QS Industries (QSI)";
                case 114: return "";
                case 115: return "Dietz Modellbahntechnik";
                case 116: return "";
                case 117: return "cT Elektronik";
                case 118: return "";
                case 119: return "W. S. Ataras Engineering";
                case 120: return "";
                case 121: return "";
                case 122: return "";
                case 123: return "Massoth Elektronik, GmbH";
                case 124: return "";
                case 125: return "ProfiLok Modellbahntechnik GmbH";
                case 126: return "";
                case 127: return "Atlas Model Railroad Products";
                case 128: return "";
                case 129: return "Digitrax";
                case 130: return "";
                case 131: return "Trix Modelleisenbahn";
                case 132: return "ZTC";
                case 133: return "Intelligent Command Control";
                case 134: return "";
                case 135: return "CVP Products";
                case 136: return "";
                case 137: return "";
                case 138: return "";
                case 139: return "RealRail Effects";
                case 140: return "";
                case 141: return "Throttle-Up (Soundtraxx)";
                case 142: return "";
                case 143: return "Model Rectifier Corp.";
                case 144: return "";
                case 145: return "Zimo Elektronik";
                case 146: return "";
                case 147: return "Umelec Ing. Buero";
                case 148: return "";
                case 149: return "Rock Junction Controls";
                case 150: return "";
                case 151: return "Electronic Solutions Ulm GmbH";
                case 152: return "";
                case 153: return "Train Control Systems";
                case 154: return "";
                case 155: return "Gebr. Fleischmann GmbH & Co.";
                case 156: return "";
                case 157: return "Kuehn Ing.";
                case 158: return "";
                case 159: return "LGB (Ernst Paul Lehmann Patentwerk)";
                case 160: return "";
                case 161: return "Modelleisenbahn GmbH (formerly Roco)";
                case 162: return "";
                case 163: return "WP Railshops";
                case 164: return "";
                case 165: return "Model Electronic Railway Group";
                case 166: return "";
                case 167: return "";
                case 168: return "";
                case 169: return "";
                case 170: return "AuroTrains";
                case 171: return "";
                case 172: return "";
                case 173: return "Arnold – Rivarossi";
                case 174: return "";
                case 175: return "";
                case 176: return "";
                case 177: return "";
                case 178: return "";
                case 179: return "";
                case 180: return "";
                case 181: return "";
                case 182: return "";
                case 183: return "";
                case 184: return "";
                case 185: return "";
                case 186: return "BRAWA Modellspielwaren GmbH & Co.";
                case 187: return "";
                case 188: return "";
                case 189: return "";
                case 190: return "";
                case 191: return "";
                case 192: return "";
                case 193: return "";
                case 194: return "";
                case 195: return "";
                case 196: return "";
                case 197: return "";
                case 198: return "";
                case 199: return "";
                case 200: return "";
                case 201: return "";
                case 202: return "";
                case 203: return "";
                case 204: return "Con-Com GmbH";
                case 205: return "";
                case 206: return "";
                case 207: return "";
                case 208: return "";
                case 209: return "";
                case 210: return "";
                case 211: return "";
                case 212: return "";
                case 213: return "";
                case 214: return "";
                case 215: return "";
                case 216: return "";
                case 217: return "";
                case 218: return "";
                case 219: return "";
                case 220: return "";
                case 221: return "";
                case 222: return "";
                case 223: return "";
                case 224: return "";
                case 225: return "Elproma Electronics Poland";
                case 226: return "";
                case 227: return "";
                case 228: return "";
                case 229: return "";
                case 230: return "";
                case 231: return "";
                case 232: return "";
                case 233: return "";
                case 234: return "";
                case 235: return "";
                case 236: return "";
                case 237: return "";
                case 238: return "NMRA Reserved";
                case 239: return "";
                case 240: return "";
                case 241: return "";
                case 242: return "";
                case 243: return "";
                case 244: return "";
                case 245: return "";
                case 246: return "";
                case 247: return "";
                case 248: return "";
                case 249: return "";
                case 250: return "";
                case 251: return "";
                case 252: return "";
                case 253: return "";
                case 254: return "";
                case 255: return "";
                default: return "";
            }
        }
    }
}
